# -*- coding: utf-8 -*-
"""SURCHARGES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKXGV_TQj9wk_Zjzno0FvZAEl5vsrfig
"""

import pandas as pd
File = pd.read_excel("Default_Surcharge.xlsx", sheet_name = "Sheet1")

File.info()

File.sample(5)

"""**MONTHLY SUCHARGE CALCULATION**"""

def OPS_Surcharge(C_Series,M_Series):
  MC_Pair = list(zip(M_Series,C_Series))
  Result, surcharge = [],[]

  Outstanding_Balance, Surcharge = [],[]
  for N_months,C in MC_Pair:
    A,s = 0,0.03
    for i in range(int(N_months)):
      A_due = (1+s)*(A+C)
      A = A_due
    Result.append(round(A_due,2))
    surcharge.append(round(A_due-(C*N_months),2))

  return Result, surcharge

#C stands for Contributions (i.e. the column in the excel table for monthly contributions)
#M, stands for number of months in default (i.e. the column in the excel table for months of default)
#A and s, stands for running amount due and surcharge percentage respectively.

"""**SURCHARGE CALCULATION -** *When monthly contributions are not the same* 👇👇👇"""

def Surcharge_Different(C_Series,M_Series):
  CM_Pair = list(zip(C_Series,M_Series))
  Result, surcharge = [],[]

  Outstanding_Balance, Surcharge = [],[]
  for C,M in CM_Pair:
    A,s = C,0.03
    for i in range(M):
      A_due = (1+s)*(A)
      A = A_due
    Result.append(round(A_due,2))
    surcharge.append(round(A_due-C,2))

  return surcharge, Result

#C stands for Contributions (i.e. the column in the excel table for monthly contributions)
#M, stands for number of months in default (i.e. the column in the excel table for months of default)
#A and s, stands for running amount due and surcharge percentage respectively.

"""**SURCHARGE FOR ONE COMPANY** 👇👇👇"""

File["Amount Due"], File["Surcharge"] = OPS_Surcharge(File["Contribution Amount Defaulted"],File["Number of Months Run"])

File["Amount Due"], File["Surcharge"] = Surcharge_Different(File["Contribution Amount Defaulted"],File["Number of Months Run"])

File.to_excel("Default_Surcharge.xlsx", index = False)